import './global.css';
import { PropsWithChildren } from 'react';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Welcome to zail -frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
