import { ApolloWrapper } from '@/components/providers';
import './global.css';
import { PropsWithChildren } from 'react';
import 'react-toastify/dist/ReactToastify.css';
import { Sidebar } from '@/components/Sidebar';
export const metadata = {
  title: 'Welcome to instagram-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        {/* Uncomment the following line to enable Apollo Client */}
        {/* <ApolloWrapper>{children}</ApolloWrapper> */}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;

