import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { MenuButtons } from '@/components/Home/leftSideBar/MenuButtonsSideBar';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <MenuButtons />
          <ApolloWrapper>{children}</ApolloWrapper>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
