'use client';
import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { MenuButtons } from '@/components/Home/leftSideBar/MenuButtonsSideBar';
import { usePathname } from 'next/navigation';
import { ToastContainer } from 'react-toastify';

// export const metadata = {
//   title: 'Welcome to example-frontend',
//   description: 'Generated by create-nx-workspace',
// };

const RootLayout = ({ children }: PropsWithChildren) => {
  const pathName = usePathname();
  const Signup = pathName.startsWith('/sign-up');
  const Login = pathName.startsWith('/log-in');

  return (
    <html lang="en">
      <body>
        {Signup || Login ? (
          <ApolloWrapper>
            {children}
            <ToastContainer position="top-right" />
          </ApolloWrapper>
        ) : (
          <div className="flex">
            <MenuButtons />
            <ApolloWrapper>
              {children}
              <ToastContainer position="top-right" />
            </ApolloWrapper>
          </div>
        )}
      </body>
    </html>
  );
};

export default RootLayout;
