import { PropsWithChildren } from 'react';
import { ApolloWrapper } from '@/components/providers';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Restaurant | Pinecone',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </ClerkProvider>
      </body>
    </html>
  );
};

export default RootLayout;
