import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import Footer from './_components/Footer';
import { AuthProvider } from './_components/context/AuthContext';
import ThemeWrapper from './_components/ThemeWrapper';
export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <ApolloWrapper>
        <AuthProvider>
          <ThemeWrapper>
            <div className="min-h-screen">{children}</div>
            <Footer />
          </ThemeWrapper>
        </AuthProvider>
      </ApolloWrapper>
    </html>
  );
};

export default RootLayout;
