import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import Footer from './_components/Footer';
import { AuthProvider } from './_components/context/AuthContext';
import ThemeWrapper from './_components/ThemeWrapper';

export const metadata = {
  title: 'Concert-Booking website',
  description: 'Generated by 2A',
};
const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en" className="font-sans">
      <body>
        <ApolloWrapper>
          <AuthProvider>
            <ThemeWrapper>
              <div className="min-h-screen">{children}</div>
              <Footer />
            </ThemeWrapper>
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
