import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import Header from './_components/Header';
import Footer from './_components/Footer';
import { AuthProvider } from './_components/context/AuthContext';
export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="dark">
        <ApolloWrapper>
          <AuthProvider>
            <Header />
            <div className="min-h-screen">{children}</div>
            <Footer />
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
