import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import LayoutClient from './_components/LayoutClient';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ApolloWrapper>
          <LayoutClient>{children}</LayoutClient>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
