export * from './HotelDetailsAboutThisProperty'
export * from './HotelDetailsAmenities';
export * from './HotelDetailsGeneralInfo';
export * from './HotelDetailsRoomTypes';
export * from './HotelDetailsFrequently';
export * from './HotelDetailsImages';
export * from './HotelDetailsPolicies'
export * from './HotelDetailsPolicies2'
export * from './HotelDetailsLocation';
export * from './HotelDetailsUpcomingBookings';