'use client';
import './global.css';
import { Button, ThemeProvider } from '@mui/material';
import { FederationProvider } from '../common';
import { theme } from '../common/theme';

export const metadata = {
  title: 'Welcome to glms-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <FederationProvider>
          <body>{children}</body>
        </FederationProvider>
      </ThemeProvider>
    </html>
  );
};
export default RootLayout;
