import { ThemeProvider } from '@/components/ThemeProvider';
import { FederationProvider } from '../common';
import './global.css';
import { ProjectHeader } from '@/components/ProjectHeader';
import { Hero } from '@/components/Hero';
import { HeroTabs } from '@/components/HeroTabs';
import { ApolloWrapper } from '@/components/providers';

export const metadata = {
  title: 'Welcome to GLMS-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <FederationProvider>
            <ApolloWrapper>
              <ProjectHeader />
              <Hero />
              <HeroTabs />
              {children}
            </ApolloWrapper>
          </FederationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
