import { PropsWithChildren } from 'react';
import { ApolloWrapper } from '@/components/providers';
import { AdminNavbar } from '@/components/AdminNavbar';

export const metadata = {
  title: 'Admin',
  description: 'Generated by create-nx-workspace',
};

const AdminLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="bg-white h-full flex flex-col">
        <ApolloWrapper>
          <header className="flex-shrink-0">
            <AdminNavbar />
          </header>

          <main className="flex-grow p-4">{children}</main>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default AdminLayout;
