import { PropsWithChildren } from 'react';
import { ApolloWrapper } from '@/components/providers';
import { AdminNavbar } from '@/components/AdminNavbar';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const AdminLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="bg-white">
        <ApolloWrapper>
          <div>
            <AdminNavbar />
            {children}
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default AdminLayout;
