import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { Footer } from '@/app/_components/Footer';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="flex flex-col gap-5">
        <ApolloWrapper>
          {children}
          <Footer />
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
