import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { Toaster } from 'sonner';
import { AuthProvider } from './(main)/_context/AuthContext';
import Layout from './(main)/layout';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="flex flex-col gap-5">
        <Toaster />
        <ApolloWrapper>
          <AuthProvider>
            <Layout>{children}</Layout>
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
