import './global.css';
import { PropsWithChildren } from 'react';
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from './providers/apollo';

export const metadata = {
  title: 'Welcome to tinder-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
