import { FederationProvider } from '../common';
import './global.css';

export const metadata = {
  title: 'Welcome to CMS-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <FederationProvider>
          <div className="flex flex-col flex-1">
            <div className="flex flex-col md:flex-row dark:bg-white ">{children}</div>
          </div>
        </FederationProvider>
      </body>
    </html>
  );
};
export default RootLayout;
