import { ThemeProvider } from '@/components/ThemeProvider';
import { FederationProvider } from '../common';
import './global.css';
import { ProjectHeader } from '@/components/ProjectHeader';
import { AuthProvider } from '@/common/providers/AuthProvider';

export const metadata = {
  title: 'Welcome to CMS-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <FederationProvider>
            <AuthProvider>
              <ProjectHeader />
              {children}
            </AuthProvider>
          </FederationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
