import { ThemeProvider } from '@/components/ThemeProvider';
import { FederationProvider } from '../common';
import './global.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { ProjectHeader } from '@/components/ProjectHeader';
import { AuthProvider } from '@/common/providers/AuthProvider';

export const metadata = {
  title: 'Welcome to CMS-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <FederationProvider>
          <AuthProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <ToastContainer>
                <ProjectHeader />
              </ToastContainer>
              {children}
            </ThemeProvider>
          </AuthProvider>
        </FederationProvider>
      </body>
    </html>
  );
};
export default RootLayout;
