import { FederationProvider } from '../common';
import './global.css';

export const metadata = {
  title: 'Welcome to HRMS-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <FederationProvider>{children}</FederationProvider>
      </body>
    </html>
  );
};
export default RootLayout;
