import { ThemeProvider } from '@/components/ThemeProvider';
import { FederationProvider } from '../common';
import './global.css';
import { ProjectHeader } from '@/components/ProjectHeader';
import { Header } from './employee-details/_components/header/Header';

export const metadata = {
  title: 'Welcome to HRMS-dashboard',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="relative">
        <FederationProvider>
          <Header />
          {children}
        </FederationProvider>
      </body>
    </html>
  );
};
export default RootLayout;
