describe('Create Employee Form', () => {
  beforeEach(() => cy.visit('/employee-details'));
  it('1.Modal should open when click on add employee button', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="addEmployeeForm"]').should('exist').should('be.visible');
  });
  it('2. When user enters no value on the inputs and click on the sign in button, it should display an error messages', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="customInput"]').eq(0).should('exist').should('contain', 'Овог оруулна уу');
    cy.get('[data-testid="customInput"]').eq(1).should('exist').should('contain', 'Нэр оруулна уу');
    cy.get('[data-testid="customInput"]').eq(2).should('exist').should('contain', 'И-мэйл оруулна уу');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').should('contain', 'Албан тушаал оруулна уу');
    cy.get('[data-testid="customInput"]').eq(4).should('exist').should('contain', 'Түвшин оруулна уу');
    cy.get('[data-testid="customInput"]').eq(5).should('exist').should('contain', 'Цалин 100 мянгаас их байх');
    cy.get('[data-testid="customInput"]').eq(7).should('exist').should('contain', 'Хэлтэс сонгоно уу');
    cy.get('[data-testid="customInput"]').eq(8).should('exist').should('contain', 'Төлөв сонгоно уу');
  });
  it('3. When the user types an invalid email, it should display invalid email message', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail');
    cy.get('[data-testid="customInput"]').eq(2).should('exist').should('contain', 'Хүчинтэй и-мэйл оруулна уу');
  });
  it('4. When the user types a job title, error message should disappear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').click();
    cy.get('[data-testid="customInput"]').eq(3).should('exist').type('Developer');
    cy.get('[data-testid="customInput"]').eq(3).should('not.contain', 'Албан тушаал оруулна уу');
  });
  it('5. When the user types a ladderLevel, error message should disappear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').click();
    cy.get('[data-testid="customInput"]').eq(3).should('exist').type('Developer');
    cy.get('[data-testid="customInput"]').eq(3).should('not.contain', 'Албан тушаал оруулна уу');
    cy.get('[data-testid="customInput"]').eq(4).should('exist').type('2');
    cy.get('[data-testid="customInput"]').eq(4).should('not.contain', 'Түвшин оруулна уу');
  });
  it('6. When the user types a valid salary, error message should disappear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').click();
    cy.get('[data-testid="customInput"]').eq(3).should('exist').type('Developer');
    cy.get('[data-testid="customInput"]').eq(3).should('not.contain', 'Албан тушаал оруулна уу');
    cy.get('[data-testid="customInput"]').eq(4).should('exist').type('2');
    cy.get('[data-testid="customInput"]').eq(4).should('not.contain', 'Түвшин оруулна уу');
    cy.get('[data-testid="customInput"]').eq(5).should('exist').type('455000');
    cy.get('[data-testid="customInput"]').eq(5).should('not.contain', 'Цалин 100 мянгаас их байх');
  });
  it('7. When the user select a department, it should display invalid departments list', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').click();
    cy.get('[data-testid="customInput"]').eq(3).should('exist').type('Developer');
    cy.get('[data-testid="customInput"]').eq(3).should('not.contain', 'Албан тушаал оруулна уу');
    cy.get('[data-testid="customInput"]').eq(4).should('exist').type('2');
    cy.get('[data-testid="customInput"]').eq(4).should('not.contain', 'Түвшин оруулна уу');
    cy.get('[data-testid="customInput"]').eq(5).should('exist').type('455000');
    cy.get('[data-testid="customInput"]').eq(5).should('not.contain', 'Цалин 100 мянгаас их байх');
    cy.get('select[name="department"]').should('exist').select('DESIGN');
    cy.get('select[name="department"]').should('have.value', 'DESIGN');
  });

  it('8. When the user select employment status, status should display', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').click();
    cy.get('[data-testid="customInput"]').eq(3).should('exist').type('Developer');
    cy.get('[data-testid="customInput"]').eq(3).should('not.contain', 'Албан тушаал оруулна уу');
    cy.get('[data-testid="customInput"]').eq(4).should('exist').type('2');
    cy.get('[data-testid="customInput"]').eq(4).should('not.contain', 'Түвшин оруулна уу');
    cy.get('[data-testid="customInput"]').eq(5).should('exist').type('455000');
    cy.get('[data-testid="customInput"]').eq(5).should('not.contain', 'Цалин 100 мянгаас их байх');
    cy.get('select[name="department"]').should('exist').select('DESIGN');
    cy.get('select[name="department"]').should('have.value', 'DESIGN');
    cy.get('select[name="employmentStatus"]').should('exist').select('FULL_TIME');
    cy.get('select[name="employmentStatus"]').should('have.value', 'FULL_TIME');
  });
  it('10. When the user fill all input, submit button is not disabled', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-cy="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-testid="customInput"]').eq(3).should('exist').click();
    cy.get('[data-testid="customInput"]').eq(3).should('exist').type('Developer');
    cy.get('[data-testid="customInput"]').eq(3).should('not.contain', 'Албан тушаал оруулна уу');
    cy.get('[data-testid="customInput"]').eq(4).should('exist').type('2');
    cy.get('[data-testid="customInput"]').eq(4).should('not.contain', 'Түвшин оруулна уу');
    cy.get('[data-testid="customInput"]').eq(5).should('exist').type('455000');
    cy.get('[data-testid="customInput"]').eq(5).should('not.contain', 'Цалин 100 мянгаас их байх');
    cy.get('select[name="department"]').should('exist').select('DESIGN');
    cy.get('select[name="department"]').should('have.value', 'DESIGN');
    cy.get('select[name="employmentStatus"]').should('exist').select('FULL_TIME');
    cy.get('select[name="employmentStatus"]').should('have.value', 'FULL_TIME');
    cy.get('[data-cy="createEmployeeBtn"]').should('not.be.disabled');
    cy.get('button[name="submitBtn"]').click()
  });
});
