describe('Create Employee Form', () => {
  beforeEach(() => cy.visit('/employee-details'));
  it('1.Modal should open when click on add employee button', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-cy="addEmployeeForm"]').should('exist').should('be.visible');
  });
  it('2. When user enters no value on the inputs and click on the sign in button, it should display an error messages', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('[data-cy="customInput"]').eq(0).should('exist').should('contain', 'Овог оруулна уу');
    cy.get('[data-cy="customInput"]').eq(1).should('exist').should('contain', 'Нэр оруулна уу');
    cy.get('[data-cy="customInput"]').eq(2).should('exist').should('contain', 'И-мэйл оруулна уу');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').should('contain', 'Хэлтэс сонгоно уу');
    cy.get('[data-cy="customInput"]').eq(4).should('exist').should('contain', 'Албан тушаал оруулна уу');
    cy.get('[data-cy="customInput"]').eq(5).should('exist').should('contain', 'Түвшин оруулна уу');
    cy.get('[data-cy="customInput"]').eq(6).should('exist').should('contain', 'Цалин оруулна уу');
    cy.get('[data-cy="customInput"]').eq(8).should('exist');
  });
  it('3. When the user types an invalid email, it should display invalid email message', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail');
    cy.get('[data-cy="customInput"]').eq(2).should('exist').should('contain', 'Хүчинтэй и-мэйл оруулна уу');
  });
  it('4. When the user select a department, it should display invalid departments list', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click()
  });
  it('5. When the user types a job title, error message should disappear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
  });
  it('6. When the user types a ladderLevel, error message should disappear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(5).should('exist').type('4')
    cy.get('[data-cy="customInput"]').eq(5).find('p').should('not.exist')
  }); it('7. When the user types a invalid salary, error message should appear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(5).should('exist').type('4')
    cy.get('[data-cy="customInput"]').eq(5).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(6).should('exist').type('8000')
    cy.get('[data-cy="customInput"]').eq(6).should('exist').should('contain', 'Цалин 100 мянгаас их байх');
  });
 it('8. When the user types a valid salary, error message should disappear', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(5).should('exist').type('4')
    cy.get('[data-cy="customInput"]').eq(5).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(6).should('exist').type('455000')
    cy.get('[data-cy="customInput"]').eq(6).find('p').should('not.exist')
  });
  it('9. When the user select employment status, status should display', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(5).should('exist').type('4')
    cy.get('[data-cy="customInput"]').eq(5).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(6).should('exist').type('455000')
    cy.get('[data-cy="customInput"]').eq(6).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(7).find('input')
    cy.get('[data-cy="customInput"]').eq(8).should('exist').click();
    cy.get('[data-cy="employmentStatusList"]').should('be.visible').eq(0).click();
  });
  it('10. When the user fill all input, submit button is not disabled', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(5).should('exist').type('4')
    cy.get('[data-cy="customInput"]').eq(5).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(6).should('exist').type('455000')
    cy.get('[data-cy="customInput"]').eq(6).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(7).find('input')
    cy.get('[data-cy="customInput"]').eq(8).should('exist').click();
    cy.get('[data-cy="employmentStatusList"]').should('be.visible').eq(0).click();
    cy.get('[data-testid="createEmployeeBtn"]').should('not.be.disabled');
  });
  it.only('11. When the user fill all input, submit button is not disabled', () => {
    cy.get('[data-cy="addEmployeeBtn"]').should('exist').should('be.visible').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('exist').click();
    cy.get('[data-testid="createEmployeeBtn"]').should('be.disabled');
    cy.get('input[name="lastName"]').type('test last name');
    cy.get('input[name="firstName"]').type('test first name');
    cy.get('input[name="email"]').type('testEmail@email.com');
    cy.get('[data-cy="customInput"]').eq(3).should('exist').click();
    cy.get('[data-cy="departmentList"]').should('be.visible').eq(0).click();
    cy.get('[data-cy="customInput"]').eq(4).should('exist').type('Developer')
    cy.get('[data-cy="customInput"]').eq(4).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(5).should('exist').type('4')
    cy.get('[data-cy="customInput"]').eq(5).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(6).should('exist').type('455000')
    cy.get('[data-cy="customInput"]').eq(6).find('p').should('not.exist')
    cy.get('[data-cy="customInput"]').eq(7).find('input')
    cy.get('[data-cy="customInput"]').eq(8).should('exist').click();
    cy.get('[data-cy="employmentStatusList"]').should('be.visible').eq(0).click();
    cy.get('[data-testid="createEmployeeBtn"]').should('not.be.disabled').click();
  });
});
