import { PropsWithChildren } from 'react';
import { ApolloWrapper } from '@/components/providers';
import { LeftSideBar } from '@/components/LeftSideBar';
import RightSideBar from '@/components/RightSideBar';
import { SuggestCard } from '@/components/SuggestCard';

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create-nx-workspace',
};

const HomeLayout = ({ children }: PropsWithChildren) => {
  return (
    <div className="flex min-w-full">
      <LeftSideBar />
      <div className="flex gap-[72px] mx-auto">
        <ApolloWrapper>
          <div>{children}</div>
        </ApolloWrapper>
        <div className="flex flex-col gap-y-4 py-10">
          <RightSideBar />
          <SuggestCard />
        </div>
      </div>
    </div>
  );
};

export default HomeLayout;
