/* eslint-disable max-lines */
/* eslint-disable no-secrets/no-secrets */
export const mockDataGetSmallPostsOne = {
  data: {
    getSmallPosts: {
      edges: [
        {
          cursor: 'Njc5MDdjNmI3Nzg1N2I3OGE0OGFlY2M0',
          node: {
            _id: '67907c6b77857b78a48aecc4',
            postImage: ['https://res.cloudinary.com/dqxstnqrf/image/upload/v1737522276/cl3ntzj3andfpaw6ndia.png'],
            caption: null,
            userId: '678e1e9179fd42a3a41c8dfe',
            carouselMediaCount: 1,
            createdAt: 1737522283372,
            commentCount: 1,
            likeCount: 0,
            hasLiked: false,
            user: {
              _id: '678e1e9179fd42a3a41c8dfe',
              userName: 'dev',
              fullName: 'devdev',
              bio: 'devedeededede',
              profileImage: 'https://res.cloudinary.com/dqxstnqrf/image/upload/q_auto,f_auto/v1738557334/464760996_1254146839119862_3605321457742435801_n.png_fgbfnt.jpg',
              hasStory: false,
              gender: 'male',
              isPrivate: false,
              email: 'dev@gmail.com',
              followingCount: 1,
              followerCount: 0,
              postCount: 4,
              latestStoryTimestamp: 0,
              seenStoryTime: 0,
              savedUsers: ['6789fe2e6ac4e4a4329b877d'],
              friendshipStatus: {
                followedBy: false,
                following: false,
                incomingRequest: false,
                outgoingRequest: false,
              },
            },
          },
        },
        {
          cursor: 'Njc5MDdiZGY3Nzg1N2I3OGE0OGFlY2My',
          node: {
            _id: '67907bdf77857b78a48aecc2',
            postImage: ['https://res.cloudinary.com/dqxstnqrf/image/upload/v1737522139/xsbgwk2f2zazagdd1tzv.png'],
            caption: null,
            userId: '678e1e9179fd42a3a41c8dfe',
            carouselMediaCount: 1,
            createdAt: 1737522143157,
            commentCount: 2,
            likeCount: 0,
            hasLiked: false,
            user: {
              _id: '678e1e9179fd42a3a41c8dfe',
              userName: 'dev',
              fullName: 'devdev',
              bio: 'devedeededede',
              profileImage: 'https://res.cloudinary.com/dqxstnqrf/image/upload/q_auto,f_auto/v1738557334/464760996_1254146839119862_3605321457742435801_n.png_fgbfnt.jpg',
              hasStory: false,
              gender: 'male',
              isPrivate: false,
              email: 'dev@gmail.com',
              followingCount: 1,
              followerCount: 0,
              postCount: 4,
              latestStoryTimestamp: 0,
              seenStoryTime: 0,
              savedUsers: ['6789fe2e6ac4e4a4329b877d'],
              friendshipStatus: {
                followedBy: false,
                following: false,
                incomingRequest: false,
                outgoingRequest: false,
              },
            },
          },
        },
        {
          cursor: 'Njc4ZTJkOWRmNTY4Zjc5NDM1ZThjZDY0',
          node: {
            _id: '678e2d9df568f79435e8cd64',
            postImage: [
              'https://res.cloudinary.com/dqxstnqrf/image/upload/v1737371027/xg47tgwe5a1opshg4veh.svg',
              'https://res.cloudinary.com/dqxstnqrf/image/upload/v1737371028/n1bulctfakusuyvobhq4.jpg',
              'https://res.cloudinary.com/dqxstnqrf/image/upload/v1737371027/uhvnypvjwier0ses0vye.svg',
            ],
            caption: 'olon zurag',
            userId: '678e1e9179fd42a3a41c8dfe',
            carouselMediaCount: 3,
            createdAt: 1737371037275,
            commentCount: 9,
            likeCount: 0,
            hasLiked: false,
            user: {
              _id: '678e1e9179fd42a3a41c8dfe',
              userName: 'dev',
              fullName: 'devdev',
              bio: 'devedeededede',
              profileImage: 'https://res.cloudinary.com/dqxstnqrf/image/upload/q_auto,f_auto/v1738557334/464760996_1254146839119862_3605321457742435801_n.png_fgbfnt.jpg',
              hasStory: false,
              gender: 'male',
              isPrivate: false,
              email: 'dev@gmail.com',
              followingCount: 1,
              followerCount: 0,
              postCount: 4,
              latestStoryTimestamp: 0,
              seenStoryTime: 0,
              savedUsers: ['6789fe2e6ac4e4a4329b877d'],
              friendshipStatus: {
                followedBy: false,
                following: false,
                incomingRequest: false,
                outgoingRequest: false,
              },
            },
          },
        },
        {
          cursor: 'Njc4ZTJjYjllMjhiZDlhNzk4MDkwMTM0',
          node: {
            _id: '678e2cb9e28bd9a798090134',
            postImage: ['https://res.cloudinary.com/dqxstnqrf/image/upload/v1737370798/ziptiy7eajt9gqg6x4sm.jpg'],
            caption: 'yesss dev ehnii post',
            userId: '678e1e9179fd42a3a41c8dfe',
            carouselMediaCount: 1,
            createdAt: 1737370809364,
            commentCount: 11,
            likeCount: 0,
            hasLiked: false,
            user: {
              _id: '678e1e9179fd42a3a41c8dfe',
              userName: 'dev',
              fullName: 'devdev',
              bio: 'devedeededede',
              profileImage: 'https://res.cloudinary.com/dqxstnqrf/image/upload/q_auto,f_auto/v1738557334/464760996_1254146839119862_3605321457742435801_n.png_fgbfnt.jpg',
              hasStory: false,
              gender: 'male',
              isPrivate: false,
              email: 'dev@gmail.com',
              followingCount: 1,
              followerCount: 0,
              postCount: 4,
              latestStoryTimestamp: 0,
              seenStoryTime: 0,
              savedUsers: ['6789fe2e6ac4e4a4329b877d'],
              friendshipStatus: {
                followedBy: false,
                following: false,
                incomingRequest: false,
                outgoingRequest: false,
              },
            },
          },
        },
        {
          cursor: 'Njc4YTY1ZjYzNjY2MDMwOWYwYmMxZmE1',
          node: {
            _id: '678a65f636660309f0bc1fa5',
            postImage: ['https://res.cloudinary.com/dqxstnqrf/image/upload/v1737123297/sfvuoronndgpvuc3kdet.svg'],
            caption: 'aaaa check check',
            userId: '6789b1cf63e287cd542f691f',
            carouselMediaCount: 2,
            createdAt: 1737123318561,
            commentCount: 0,
            likeCount: 0,
            hasLiked: false,
            user: {
              _id: '6789b1cf63e287cd542f691f',
              userName: 'iam_tuugii',
              fullName: 'tuguldur namjildorj',
              bio: '',
              profileImage: 'https://res.cloudinary.com/dqxstnqrf/image/upload/q_auto,f_auto/v1738557334/464760996_1254146839119862_3605321457742435801_n.png_fgbfnt.jpg',
              hasStory: false,
              gender: 'not_know',
              isPrivate: false,
              email: 'namjildorjtuguldur1234@gmail.com',
              followingCount: 0,
              followerCount: 0,
              postCount: 0,
              latestStoryTimestamp: 0,
              seenStoryTime: 0,
              savedUsers: [],
              friendshipStatus: {
                followedBy: false,
                following: false,
                incomingRequest: false,
                outgoingRequest: false,
              },
            },
          },
        },
        {
          cursor: 'Njc4YTUwY2UzNjY2MDMwOWYwYmMxZmEz',
          node: {
            _id: '678a50ce36660309f0bc1fa3',
            postImage: ['https://res.cloudinary.com/dqxstnqrf/image/upload/v1737117875/iljh7hj3dgoye5jnsd7q.svg'],
            caption: 'eeee yuuu weee',
            userId: '6789b1cf63e287cd542f691f',
            carouselMediaCount: 2,
            createdAt: 1737117902935,
            commentCount: 0,
            likeCount: 0,
            hasLiked: false,
            user: {
              _id: '6789b1cf63e287cd542f691f',
              userName: 'iam_tuugii',
              fullName: 'tuguldur namjildorj',
              bio: '',
              profileImage: 'https://res.cloudinary.com/dqxstnqrf/image/upload/q_auto,f_auto/v1738557334/464760996_1254146839119862_3605321457742435801_n.png_fgbfnt.jpg',
              hasStory: false,
              gender: 'not_know',
              isPrivate: false,
              email: 'namjildorjtuguldur1234@gmail.com',
              followingCount: 0,
              followerCount: 0,
              postCount: 0,
              latestStoryTimestamp: 0,
              seenStoryTime: 0,
              savedUsers: [],
              friendshipStatus: {
                followedBy: false,
                following: false,
                incomingRequest: false,
                outgoingRequest: false,
              },
            },
          },
        },
      ],
      pageInfo: {
        startCursor: 'Njc5MDdjNmI3Nzg1N2I3OGE0OGFlY2M0',
        endCursor: 'Njc4YTUwY2UzNjY2MDMwOWYwYmMxZmEz',
        hasNextPage: true,
      },
    },
  },
};
export const mockDataGetSmallPostsEdgesNull = {
  data: {
    getSmallPosts: {
      edges: null,
      pageInfo: {
        startCursor: 'Njc5MDdjNmI3Nzg1N2I3OGE0OGFlY2M0',
        endCursor: 'Njc4YTUwY2UzNjY2MDMwOWYwYmMxZmEz',
        hasNextPage: false,
      },
    },
  },
};
export const mockDataGetSmallPostsEdgesLengthZero = {
  data: {
    getSmallPosts: {
      edges: [],
      pageInfo: {
        startCursor: 'Njc5MDdjNmI3Nzg1N2I3OGE0OGFlY2M0',
        endCursor: 'Njc4YTUwY2UzNjY2MDMwOWYwYmMxZmEz',
        hasNextPage: false,
      },
    },
  },
};
