services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  crawler:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
    deploy:
      replicas: 3  # Run 3 parallel crawler workers
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - .:/app

volumes:
  redis_data:
    driver: local
