import { PropsWithChildren } from 'react';

import { ApolloWrapper } from '@/components/providers';
import AdminHeader from './_components/Header';


export const metadata = {
  title: 'Restaurant | Pinecone',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
       
          <ApolloWrapper>
            <AdminHeader/>
            {children}
            </ApolloWrapper>
      
      </body>
    </html>
  );
};

export default RootLayout;
