import './global.css';
import { PropsWithChildren } from 'react';
import 'react-toastify/dist/ReactToastify.css';
import { Navbar } from './components/Navbar';

export const metadata = {
  title: 'Welcome to restaurant-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <div>
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
