import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper, CartProvider } from '@/components/providers';
import { Toaster } from '@/components/ui/sonner';
export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="mx-auto">
        <ApolloWrapper>
          <CartProvider>
            {children}
            <Toaster />
          </CartProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
